In [28]:
import math
x=4
1/(1+math.exp(-x))

0.9820137900379085

In [30]:
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [32]:
print(sigmoid(4))

0.9820137900379085


In [34]:
import numpy as np
x=np.array((1,2,3))
print(np.exp(-x))

[0.36787944 0.13533528 0.04978707]


In [36]:
y=np.array((1,6,7))
print(y+1)

[2 7 8]


In [50]:
def np_sigmoid(arr):
    return 1/(1+np.exp(-arr))

In [52]:
np_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [56]:
def gradient(x):
    return np_sigmoid(x)*(1-np_sigmoid(x))

In [58]:
gradient(x)

array([0.19661193, 0.10499359, 0.04517666])

In [80]:
def reshape_img(img):
    return img.reshape(img.shape[0] * img.shape[1] * img.shape[2],1)

image = np.array([[[0.468534, 0.456467, 0.657683],
                   [0.564675, 0.464534, 0.467654],
                   [0.245232, 0.685984, 0.569804]],
                  
                  [[0.468534, 0.456467, 0.657683],
                   [0.564675, 0.464534, 0.467654],
                   [0.245232, 0.685984, 0.569804]],
                  
                  [[0.468534, 0.456467, 0.657683],
                   [0.564675, 0.464534, 0.467654],
                   [0.245232, 0.685984, 0.569804]]])

reshaped_img = reshape_img(image)
print(reshaped_img)


[[0.468534]
 [0.456467]
 [0.657683]
 [0.564675]
 [0.464534]
 [0.467654]
 [0.245232]
 [0.685984]
 [0.569804]
 [0.468534]
 [0.456467]
 [0.657683]
 [0.564675]
 [0.464534]
 [0.467654]
 [0.245232]
 [0.685984]
 [0.569804]
 [0.468534]
 [0.456467]
 [0.657683]
 [0.564675]
 [0.464534]
 [0.467654]
 [0.245232]
 [0.685984]
 [0.569804]]


In [74]:
def normalized(x):
    norm=np.linalg.norm(x,axis=1,keepdims=True)
    return x/norm

In [78]:
img=np.array([[0,100,4],[2,6,4]])

print(normalized(img))

[[0.         0.99920096 0.03996804]
 [0.26726124 0.80178373 0.53452248]]


In [82]:
def softmax(x):
    x=np.exp(x)
    norm=np.linalg.norm(x,axis=1,keepdims=True)
    return x/norm
    
    
    

In [84]:
x=[[1,4,7,3],
   [4,8,5,9]]

In [86]:
print(softmax(x))

[[0.00247526 0.04971701 0.9985928  0.01828987]
 [0.00632256 0.34519987 0.01718649 0.93835052]]


In [88]:
import time

In [100]:
x=[1,6,3,5,2,7,5,7,8,2,9,3,9,3,9,5,1,8]
y=[3,5,2,9,6,7,2,8,5,1,9,3,0,2,4,6,8,3]

start_time = time.process_time()
end_time = time.process_time()
dot = 0
for i in range(len(x)):
    dot += x[i] * y[i]
elapsed_time = 1000* (end_time - start_time)

print(dot)
print(elapsed_time)

145
-15.625
